# -*- coding: utf-8 -*-
"""Untitled65.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1soptcrp1u6UPMVKIs28cJ6YhQdZ_3_yd
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0,2*np.pi,100)
y = np.sin(x)
plt.subplot(221)
plt.plot(x,y, 'bo', label='sin(x)')
plt.subplot(222)
plt.plot(x, np.cos(x), 'c+', label='cos(x)')
plt.subplot(223)
plt.ylim(-15, 15)
plt.plot(x, np.tan(x), 'k')
plt.subplot(224)
plt.plot(x, np.arccos(x), 'rx')
plt.legend()

import numpy as np
import matplotlib.pyplot as plt

def f(x):
  if np.abs(x)<= 1:
    return x
  if 1<x<=2:
    return x**2
  else:
    return 5
x = np.linspace(0,2*np.pi,100)
y = np.zeros(len(x))
for i in range(len(x)):
  y[i] = f(x[i])
plt.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

def f(x):
  if np.abs(x)<= 1:
    return x
  if 1<x<=2:
    return x**2
  else:
    return 5
x = np.linspace(0,2*np.pi,100)
lista = []
for i in x:
  lista.append(f(i))
  plt.plot(x,y)